"""updated columns

Revision ID: 5df3c743173e
Revises: d947edd21295
Create Date: 2023-08-07 16:01:10.591483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df3c743173e'
down_revision: Union[str, None] = 'd947edd21295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theaters', sa.Column('theater_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theaters', 'theater_name')
    # ### end Alembic commands ###
