"""<descriptive message>

Revision ID: ba452e8913c4
Revises: 
Create Date: 2023-08-07 15:46:12.086140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba452e8913c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theaters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('goer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goer_id'], ['goers.id'], name=op.f('fk_theaters_goer_id_goers')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_theaters_movie_id_movies')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theaters')
    op.drop_table('movies')
    op.drop_table('goers')
    # ### end Alembic commands ###
